services:
  sendmind-hub:
    image: seninder/sendmind-hub:latest
    depends_on:
      - postgres
      - redis
    platform: linux/amd64
    ports:
     - "8080:8080"
    networks:
      - app-network
    restart: always
    environment:
      SENDMIND_POSTGRES_ADDR: ${SENDMIND_POSTGRES_ADDR}
      SENDMIND_POSTGRES_USER: ${SENDMIND_POSTGRES_USER}
      SENDMIND_POSTGRES_PASSWORD: ${SENDMIND_POSTGRES_PASSWORD}
      SENDMIND_POSTGRES_DB: ${SENDMIND_POSTGRES_DB}
      SENDMIND_SECRET_KEY: ${SENDMIND_SECRET_KEY}
      SENDMIND_GOOGLE_KEY_PATH: ${SENDMIND_DOCKER_GOOGLE_KEY_PATH}
      SENDMIND_FIREBASE_KEY_PATH: ${SENDMIND_DOCKER_FIREBASE_KEY_PATH}
      SENDMIND_ADMIN_API_KEY: ${SENDMIND_ADMIN_API_KEY}
      SENDMIND_ADMIN_ALLOWED_IPS: ${SENDMIND_ADMIN_ALLOWED_IPS}
      SENDMIND_OPENAI_API_KEY: ${SENDMIND_OPENAI_API_KEY}
      SENDMIND_APPLE_APP_PASSWORD: ${SENDMIND_APPLE_APP_PASSWORD}
      SENDMIND_PACAPACA_APP_ID: ${SENDMIND_PACAPACA_APP_ID}
      SENDMIND_REDIS_ADDR: redis:6379
      SENDMIND_GLITCHTIP_DSN: ${SENDMIND_GLITCHTIP_DSN}
      SENDMIND_ENVIRONMENT: ${SENDMIND_ENVIRONMENT}
    volumes:
          - ${SENDMIND_GOOGLE_KEY_PATH}:${SENDMIND_DOCKER_GOOGLE_KEY_PATH}
          - ${SENDMIND_FIREBASE_KEY_PATH}:${SENDMIND_DOCKER_FIREBASE_KEY_PATH}

  x-environment: &default-environment
    DATABASE_URL: postgres://${SENDMIND_POSTGRES_USER}:${SENDMIND_POSTGRES_PASSWORD}@postgres:5432/glitchtip}
    SECRET_KEY: ${SENDMIND_SECRET_KEY}
    PORT: 8000
    EMAIL_URL: ${GLITCHTIP_EMAIL_URL:-consolemail://}
    GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN:-http://localhost:8000}
    DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL:-sendminder@gmail.com}
    CELERY_WORKER_AUTOSCALE: "1,3"

  x-depends_on: &default-depends_on
    - postgres
    - redis

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    networks:
      - app-network
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${SENDMIND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SENDMIND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SENDMIND_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads

  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    networks:
      - app-network
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads

  migrate:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    networks:
      - app-network
    command: ./bin/run-migrate.sh
    environment: *default-environment

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata
    networks:
      - app-network
    ports:
      - "19999:19999"
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    environment:
      - NETDATA_ENABLE_PROMETHEUS=yes
      - NETDATA_ENABLE_GO=yes
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/os-release:ro
      - ./netdata/netdata.conf:/etc/netdata/netdata.conf
      - ./netdata/go.d.conf:/etc/netdata/go.d.conf

volumes:
  portainer_data:
  pg-data:
  netdata_config:
  netdata_lib:
  netdata_cache:
  redis_data:
  uploads:

networks:
  app-network:
    driver: bridge
