services:
  sendmind-hub:
    image: seninder/sendmind-hub:latest
    depends_on:
      - postgresql
    platform: linux/amd64
    ports:
     - "8080:8080"
    networks:
      - app-network
    restart: always
    environment:
      SENDMIND_POSTGRES_ADDR: ${SENDMIND_POSTGRES_ADDR}
      SENDMIND_POSTGRES_USER: ${SENDMIND_POSTGRES_USER}
      SENDMIND_POSTGRES_PASSWORD: ${SENDMIND_POSTGRES_PASSWORD}
      SENDMIND_POSTGRES_DB: ${SENDMIND_POSTGRES_DB}
      SENDMIND_SECRET_KEY: ${SENDMIND_SECRET_KEY}
      SENDMIND_GOOGLE_KEY_PATH: ${SENDMIND_DOCKER_GOOGLE_KEY_PATH}
      SENDMIND_FIREBASE_KEY_PATH: ${SENDMIND_DOCKER_FIREBASE_KEY_PATH}
      SENDMIND_ADMIN_API_KEY: ${SENDMIND_ADMIN_API_KEY}
      SENDMIND_ADMIN_ALLOWED_IPS: ${SENDMIND_ADMIN_ALLOWED_IPS}
      SENDMIND_OPENAI_API_KEY: ${SENDMIND_OPENAI_API_KEY}
      SENDMIND_APPLE_APP_PASSWORD: ${SENDMIND_APPLE_APP_PASSWORD}
      SENDMIND_PACAPACA_APP_ID: ${SENDMIND_PACAPACA_APP_ID}
    volumes:
          - ${SENDMIND_GOOGLE_KEY_PATH}:${SENDMIND_DOCKER_GOOGLE_KEY_PATH}
          - ${SENDMIND_FIREBASE_KEY_PATH}:${SENDMIND_DOCKER_FIREBASE_KEY_PATH}
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${SENDMIND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SENDMIND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SENDMIND_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata
    networks:
      - app-network
    ports:
      - "19999:19999"
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    environment:
      - NETDATA_ENABLE_PROMETHEUS=yes
      - NETDATA_ENABLE_GO=yes
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/os-release:ro
      - ./netdata/netdata.conf:/etc/netdata/netdata.conf
      - ./netdata/prometheus.conf:/etc/netdata/go.d/prometheus.conf
      - ./netdata/go.d.conf:/etc/netdata/go.d.conf

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${SENDMIND_PG_ADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${SENDMIND_PG_ADMIN_PW}
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin

volumes:
  portainer_data:
  postgres_data:
  netdata_config:
  netdata_lib:
  netdata_cache:
  # pgadmin_data:

networks:
  app-network:
    driver: bridge
